### PR TITLE
Fix 4th issue

### PR DESCRIPTION
**Pull request by Sarween**
I had changed the <td> tag to <th> tag for the table header and solve issue #17

### CODE REVIEW

**Comment by ZHIYAN2222** [comment]
I think it is ok

**Comment by PUAJINGSHENG** [comment]
Yes, I agree with Wai's opinion

**Review by PUAJINGSHENG — APPROVED** [review]
I think it is ok

**Review by ZHIYAN2222 — APPROVED** [review]
I approve with the changes

**Pull request merged**
