### PR TITLE
Add title to the document

### PR DESCRIPTION
**Pull request by PUAJINGSHENG**
Add title so that user can know what is the page about and solve #24

### CODE REVIEW

**Review by YS0242 — APPROVED** [review]
I agree with the changes.

**Review by Sarween — APPROVED** [review]
I am ok with the adding title.

**Comment by PUAJINGSHENG** [comment]
Since all agree, then I merge ok?

**Comment by YS0242** [comment]
Ok

**Comment by Sarween** [comment]
Ok, merge it

**Comment by ZHIYAN2222** [comment]
Ok,agree

**Pull request merged**
